version: '3.1'

services:
  cache:
    image: redis:7.0
    restart: always
    ports:
      - '6379:6378'
    command: redis-server --save 20 1 --loglevel warning
    network_mode: host

  object-store:
    build:
      context: "."
    restart: always
    depends_on:
      - cache
    environment:
      DB_HOST: cache
      DB_PORT: 6379
    network_mode: host